language: cpp
jobs:
  include:

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-7 CXX=g++-7"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-8 CXX=g++-8"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-7
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-7 CXX=clang++-7"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-8
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-8 CXX=clang++-8"
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-9 CXX=clang++-9"
before_install:
  - pip install --user cpp-coveralls
before_script:
  - eval "${MATRIX_EVAL}"
script:
  - mkdir build && cd build
  - cmake ..
  - make
  - make test && cd test
  - ./Test
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'